# Generated by Django 5.0.6 on 2024-06-22 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('course_section_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_and_section', models.CharField(max_length=55)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'course_section',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('student_id_number', models.CharField(max_length=55)),
                ('first_name', models.CharField(max_length=55)),
                ('middle_name', models.CharField(blank=True, max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('course_and_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangocrudsr.coursesection')),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
